"""empty message

Revision ID: 80145db01f31
Revises: 58cf68a53797
Create Date: 2024-11-09 19:24:08.196869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80145db01f31'
down_revision = '58cf68a53797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
